services:
    web:
        build: .
        depends_on:
            redis:
                condition: service_healthy
        command: bash -c "
            python src/preprocess.py 
            && python src/train.py 
            && python src/predict.py -m LOG_REG -t func
            && coverage run src/unit_tests/test_preprocess.py
            && coverage run -a src/unit_tests/test_training.py
            && coverage run -a src/unit_tests/test_database.py
            && coverage run -a src/unit_tests/test_app.py
            && coverage report -m
            && (python src/app.py --model LOG_REG &) 
            && sleep 30
            && curl -X GET http://localhost:8000/
            && curl -X POST http://localhost:8000/predict \
                    -H 'Content-Type":" application/json' \
                    --data-binary @tests/test_0.json"
        ports:
            - 8000:8000
        image: zarus03/ml-big-data-lab-2:latest
    redis:
        image: redis:latest
        command: bash -c "redis-server --requirepass $$REDIS_PASSWORD"
        ports:
            - 6379:6379
        env_file:
            - .env
        healthcheck:
            test: ["CMD", "redis-cli", "-a", "$$REDIS_PASSWORD", "ping"]
            interval: 1s
            timeout: 2s
            retries: 10
